artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz"  
  local_data_file: artifacts/data_ingestion/mnist.npz
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  data_files:
    - artifacts/data_ingestion/x_train.npy
    - artifacts/data_ingestion/y_train.npy
    - artifacts/data_ingestion/x_test.npy
    - artifacts/data_ingestion/y_test.npy
  stats_file: artifacts/data_validation/stats


data_transformation:
  root_dir: artifacts/data_transformation
  transformed_train_dir: artifacts/data_transformation/train
  transformed_test_dir: artifacts/data_transformation/test
  batch_size: 32


model_training:
  root_dir: artifacts/model_training
  model_dir: artifacts/model_training/model
  model_file: mnist_cnn.h5
  evaluation_file: evaluation.txt
  epochs: 10
  batch_size: 64
  learning_rate: 0.001
  transformed_train_dir: artifacts\data_transformation\train
  transformed_test_dir: artifacts\data_transformation\test
